---

- name: ec2 | Provision a set of instances
  ec2:
     state: "{{ aws_ec2_state | default(omit) }}"
     group: "{{ aws_ec2_group | default(omit) }}"
     group_id: "{{ aws_ec2_group_id | default(omit) }}"
     instance_type: "{{ aws_ec2_instance_type }}"
     image: "{{ aws_ec2_image }}"
     region: "{{ aws_ec2_region }}"
     wait: "{{ aws_ec2_wait | default(omit) }}"
     exact_count: "{{ aws_ec2_exact_count | default(omit) }}"
     count_tag: "{{ aws_ec2_count_tag | default(omit) }}"
     keypair: "{{ aws_ec2_keypair  | default(omit) }}"
     user_data: "{{ aws_ec2_user_data | default(omit) }} "
     instance_tags: "{{ aws_ec2_instance_tags | default(omit) }}"
     assign_public_ip: "{{ aws_ec2_assign_public_ip | default(omit) }}"
     vpc_subnet_id: "{{ aws_ec2_vpc_subnet_id | default(omit) }}"
     zone: "{{ aws_ec2_zone | default(omit) }}"
     volumes: "{{ aws_ec2_volumes | default(omit) }}"
     monitoring: "{{ aws_ec2_monitoring | default(omit) }}"
     aws_ec2_access_key: "{{ aws_ec2_access_key | default(omit) }}"
     aws_ec2_secret_key: "{{ aws_ec2_secret_key | default(omit) }}"
  connection: local
  delegate_to: localhost
  become: False
  register: ec2_server
