---

# Todo:
# 1- multi count issue, should loop if not one 2 one mappining
# 2- Might need change to private interface or custom ec2 as it default uses public

- name: ssh | Waiting for ssh port to open ansible_ssh_host
  wait_for:
    port="{{ ansible_ssh_port | default('22') }}"
    host="{{ ansible_ssh_host }}"
    delay="{{ aws_ec2_connection_delay }}"
    delay=1
    timeout=5
  register: ansible_ssh_working
  ignore_errors: yes
  when: ansible_ssh_host is defined

- name: ssh | Wait for ssh port to open on FQDN
  wait_for:
    port="{{ ansible_ssh_port | default('22') }}"
    host="{{ inventory_hostname }}"
    delay=1
    timeout=5
    search_regex="{{ aws_ec2_connection_string | default(omit) }}"
  register: fqdn_working
  ignore_errors: yes
  when: ansible_ssh_working | skipped or ansible_ssh_working | failed

- name: ssh | Set ansible_ssh_host to IP for initial communication (to avoid DNS delay) and default user
  set_fact:
    ansible_ssh_host: "{{ ec2_server.tagged_instances[0].public_ip }}"
    ansible_ssh_user: "{{ aws_ec2_default_user }}"
  when: fqdn_working | failed

# If we reach this point and unable to connect than it will fail
- name: ssh | Wait for ssh port to open on ec2 public dns
  wait_for:
    port="{{ ansible_ssh_port | default('22') }}"
    host="{{ ansible_ssh_host }}"
    delay="{{ aws_ec2_connection_delay }}"
    timeout="{{ aws_ec2_connection_timeout }}"
    search_regex="{{ aws_ec2_connection_string | default(omit) }}"
  when: ec2_server | changed
